### ISSUE TITLE
Question on Constructing the "Tele-neg" Sets

### ISSUE THREAD

**Issue by HansiZeng** [OpenMatch/ANCE-Tele#1]
Hi Sun Si,
Congrats on your amazing job! Both the idea and results are very impressive. 

I have one question on how you construct the "Tele-neg" set for each query. From equations (4) (5) (6) of your paper, it seems like you create the new "Tele-neg" set by merging "ANCE-neg", old "Tele-neg", and "lookahead-neg". The sampling coefficient for "ANCE-neg" and "lookahead-neg" are \alpha and \beta, and both of them are equal to 0.5 (the best hyper-parameter you mention in the paper). 

But from your code ```preprocess/combine_marco_negative.py```, it seems like you just directly merge two sets without any sampling coefficient. Can I know which part of your code contains the sampling coefficients for "ANCE-neg" and "lookahead-neg"?

Best wishes,
Hansi Zeng

**Comment by SunSiShining** [comment]
Hi Hansi, 
Sorry for the late reply, glad you like our work!  

Our analysis found that ANCE-Tele is insensitive to different α and β (Table 2 in the paper). The results reported in Table 1 can be reproduced by simply keeping the ratios between the different negative sources the same (half-half). The code in `preprocess/combine_marco_negative.py` can do this now.  Hence, we do not provide additional preprocessing methods to generate different α and β.

I hope my reply is helpful.
Si Sun :D
E-mail: s-sun17@mails.tsinghua.edu.cn

**Comment by SunSiShining** [comment]
No update; this issue closed
